import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import util from "@/lib/util";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={util(inter.className, 'min-h-screen antialiased')}>
        <Providers>
        <main className="h-screen bg-bk">
          {children}
        </main>
        </Providers>
      </body>
    </html>
  );
}
